GET http://localhost:3001/power/10

###

GET http://localhost:3001/power/9

###

GET http://localhost:3001/power/2

###

GET http://localhost:3001/power/25

###

GET http://localhost:3001/power

###

GET http://localhost:3001/sum/7/5

###

GET http://localhost:3001/sum/5/7

###

GET http://localhost:3001/sum/8/-20

###

GET http://localhost:3001/sum/100/30

###

GET http://localhost:3001/reversed/computer

###

GET http://localhost:3001/reversed/express

###

GET http://localhost:3001/reversed/Ieva

###

GET http://localhost:3001/multiply/7/8

###

GET http://localhost:3001/multiply/2/3

###

GET http://localhost:3001/multiply/-9/2

###

GET http://localhost:3001/is-even/5

###

GET http://localhost:3001/is-even/7

###

GET http://localhost:3001/is-even/4

###

GET http://localhost:3001/fullname/Ieva/Jaksaityte

###

GET http://localhost:3001/fullname/John/Smith

###

GET http://localhost:3001/average/8/5/6

###

GET http://localhost:3001/average/8/8/9

###

GET http://localhost:3001/first-last/computer

###

GET http://localhost:3001/first-last/express

###

GET http://localhost:3001/word-repeat/computer/2

###

GET http://localhost:3001/word-repeat/ha/5

###

GET http://localhost:3001/word-info/computer

###

GET http://localhost:3001/word-info/Chair

###

GET http://localhost:3001/word-info/biRD
