GET http://localhost:3000

###

GET http://localhost:3000/about

###

GET https://devmastered-express.up.railway.app/about

###

GET http://localhost:3000/contact

###

GET http://localhost:3000/unique

###

GET http://localhost:3000/store/details

### Incorect way of reaching store details:

GET http://localhost:3000/store

###

GET http://localhost:3000/product

###

GET http://localhost:3000/user/details

###

GET http://localhost:3000/blog/latest

###

GET http://localhost:3000/pet

###

GET http://localhost:3000/car

###

GET http://localhost:3000/book

###

GET http://localhost:3000/movie

###

GET http://localhost:3000/student

###

GET http://localhost:3000/city
